spring.application.name=photomodel-api
jasypt.password.encoder=d8570146cf86011d3179a57009f22e63
jwt.secret.key=sdfhaskjhDFDSAHksjhKSFH123ºKfdhkj
jwt.expiration.key=10
server.port=8081
spring.data.mongodb.uri=mongodb+srv://pablofguillen1503_db_user:5tTjLEhI3AFBf76V@photomodel.zbj5fg1.mongodb.net/photomodel
